version: "3.7"

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    container_name: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks: 
      - app-net
      
  test-db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test
    container_name: postgres-test
    volumes:
      - ./pgdata_test:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks: 
      - app-net

  sessions:
    image: redis:6.2-alpine
    volumes:
      - ./redis_data:/redis/data
    ports:
      - '6379:6379'
    networks: 
      - app-net

  app:
    build:
      context: .
      target: install-dependencies
    container_name: nest-docker-postgres
    environment:
      - NODE_ENV=development
    ports:
      - '3000:3000'
      - '9229:9229'
    depends_on:
      - db
      - sessions
    command: yarn start:inspect
    volumes:
      - ./src:/user/src/app/src
    networks: 
      - app-net

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin
    ports:
      - '5050:80'
    depends_on:
      - db
    networks: 
      - app-net

networks:
  app-net:
    driver: bridge